### ISSUE TITLE
After updating to v1.2.6, entities are unavailable

### ISSUE THREAD

**Issue by waltlillyman** [JohNan/home-assistant-plaato#15]
After updating Plaato in HACS from v1.2.5 to v1.2.6, my Plaato Keg entities are unavailable in HA.
After restarting HA core v2021.2.3 (docker container on Ubuntu 18.04), these log entries appear:
```
2021-02-12 20:41:42 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Third Keg for plaato
2021-02-12 20:41:42 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Right Keg for plaato
2021-02-12 20:41:42 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Left keg for plaato
```
After reinstalling v1.2.5 and restarting HA Core, my Plaato keg entities are available.

**Comment by JohNan** [comment]
I made a descition to not bump the version in 1.2.6 of the integration because it needed some kind of migration to pass the tests in core. 

But the version was bumped in 1.2.5 hence the inconsistency and the error message. Are you willing to try update again and re-add the devices and see if it solves it?

**Comment by waltlillyman** [comment]
Yes, I removed the integration completely, restarted HA, added the integration v1.2.6, pasted in my three Keg tokens, and restarted HA. It threw errors, so I restarted HA, again, and the same errors persist, (pasted below). Next I'll try a fresh install of 1.2.5.
```
2021-02-13 12:19:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Keg for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/plaato/sensor.py", line 16, in <module>
    from ...core import callback
ValueError: attempted relative import beyond top-level package
2021-02-13 12:19:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Keg for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/plaato/sensor.py", line 16, in <module>
    from ...core import callback
ValueError: attempted relative import beyond top-level package
2021-02-13 12:19:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Keg for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/plaato/sensor.py", line 16, in <module>
    from ...core import callback
ValueError: attempted relative import beyond top-level package
```

**Comment by waltlillyman** [comment]
After removing the integration completely, restarting HA, installing v1.2.5, pasting in my tokens, and restarting HA, the errors no longer appear and all of my Plaato Keg entities are updating successfully.

**Comment by JohNan** [comment]
Fixed the error in https://github.com/JohNan/home-assistant-plaato/pull/16
I'm going to create a new release.

**Comment by waltlillyman** [comment]
Updating to v1.2.7 from v1.2.5 failed with the "`Migration handler not found`" errors, however uninstall and install of v1.2.7 succeeded. Thanks for your efforts, @JohNan!

**Comment by JohNan** [comment]
Yes, I won't do anything about the migration handler. I'm glad to hear that the reinstall worked through!
