### ISSUE TITLE
Only two Keg Sensors Showing Up

### ISSUE THREAD

**Issue by Tyfosho** [JohNan/home-assistant-plaato#17]
With the latest update, I'm only getting the Pouring and Leaking sensors showing up in Home Assistant. I think this error in the logs may be related.

```
Logger: homeassistant.config_entries
Source: custom_components/plaato/sensor.py:16
First occurred: 10:31:07 PM (1 occurrences)
Last logged: 10:31:07 PM

Error setting up entry Keg for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/plaato/sensor.py", line 16, in <module>
    from ...core import callback
ValueError: attempted relative import beyond top-level package
```

**Comment by JohNan** [comment]
Should be fixed in this PR https://github.com/JohNan/home-assistant-plaato/pull/16 and published in latest version 1.2.7
